[settings]

[settings.ruby]
compile = false

[settings.node]
default_packages_file = "~/.default-npm-packages"

[tools]
aube = "latest"
bun = "latest"
"cargo:abtop" = "latest"
"gem:colorls" = "latest"
node = "lts"
"npm:clawhub" = "latest"
"npm:@jackwener/opencli" = "latest"
"npm:@google/gemini-cli" = "latest"
ruby = "latest"
rust = "latest"
