[ghostty]
files = { "ghostty/config.ghostty" = "~/Library/Application Support/com.mitchellh.ghostty/config.ghostty" }

[zsh]
files = { "zsh/.zshrc" = "~/.zshrc" }

[vim]
files = { "vim/.vimrc" = "~/.vimrc" }

[bash]
files = { "bash/.bashrc" = "~/.bashrc", "bash/.bash_profile" = "~/.bash_profile" }

[manico]
files = { "manico/sync.sh" = "manico/sync.sh", "manico/settings.txt" = "manico/settings.txt" }